Refactor Terraform plan and apply steps in workflow

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -72,9 +72,16 @@ jobs:
 
       - name: Terraform Plan
         id: plan
-        run: terraform plan -out=tfplan -detailed-exitcode
+        run: |
+          set +e
+          terraform plan -out=tfplan -detailed-exitcode 
+          code=$?
+          echo "code=$code" >> "$GITHUB_OUTPUT"
+          [ "$code" -eq 1 ] && exit 1 || true
+          # Exit code 0 apply is skipped.
+          # Exit code 2 apply runs.
+          # Exit code 1 job fails.
         working-directory: ./terraform-config
-        continue-on-error: true
         env:
           TF_VAR_domain_name: ${{ secrets.DOMAIN_NAME }}
           TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
@@ -82,7 +89,7 @@ jobs:
 
       - name: Terraform Apply
         id: apply
-        if: steps.plan.outcome == 'failure'  
+        if: steps.plan.outcome == '2'  
         run: terraform apply -auto-approve tfplan
         working-directory: ./terraform-config
         env:
